#!/bin/bash
# Compile Eibriel's godot-tts-079 data (MIT code, CC-BY-4.0 data;
# https://codeberg.org/Eibriel/godot-tts-079) into tts079_data.h, so the
# synthesizer is one self-contained binary.
# Usage: gen-data.sh ADDON_DIR > tts079_data.h   (ADDON_DIR = .../addons/tts_079)
set -euo pipefail
d="${1:?addon dir}/data"

echo "/* Generated by gen-data.sh from godot-tts-079 (Eibriel, CC-BY-4.0 data). */"
echo "#include <stdint.h>"
echo

echo "/* G2P rules, per letter in their order: letter, rctx, lctx, bctx, phon. */"
echo "typedef struct { char letter; const char *rctx, *lctx, *bctx, *phon; } Rule;"
echo "static const Rule RULES[] = {"
jq -r --arg q "'" 'to_entries[] | .key as $k | .value[] |
  "  {\($q)\($k)\($q), \(.rctx|@json), \(.lctx|@json), \(.bctx|@json), \(.phon|@json)},"' \
  "$d/g2p_rules.json"
echo "};"
echo

echo "/* Transitions: left, right phoneme; t1, t1_rev, t2, t2_rev (-1: none). */"
echo "typedef struct { int l, r, t1, t1_rev, t2, t2_rev; } Trans;"
echo "static const Trans TRANS[] = {"
jq -r '.transition_table | to_entries[] | (.key | split(",")) as $lr |
  "  {\($lr[0]), \($lr[1]), \(.value.t1 // -1), \(if .value.t1_rev then 1 else 0 end), \(.value.t2 // -1), \(if .value.t2_rev then 1 else 0 end)},"' \
  "$d/tables.json"
echo "};"
echo

echo "/* Segment lists, each list contiguous and in order: ptr, period_len, is_voiced, block_idx. */"
echo "typedef struct { int ptr, period_len, is_voiced, block_idx; } Seg;"
echo "static const Seg SEGS[] = {"
jq -r '.segment_lists | to_entries[] | .key as $p | .value[] |
  "  {\($p), \(.period_len), \(if .is_voiced then 1 else 0 end), \(.block_idx | floor)},"' \
  "$d/tables.json"
echo "};"
echo

echo "/* blocks.bin: length-prefixed unsigned 8-bit PCM blocks. */"
echo "static const uint8_t BLOCKS_BIN[] = {"
od -An -v -tu1 "$d/blocks.bin" | sed 's/  */ /g; s/^ //; s/ /, /g; s/$/,/'
echo "};"
